server:
  port: 8080

tabuyos:
  one:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/tabuyos
      username: tabuyos
      password: tabuyos
  two:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/tabuyos
      username: tabuyos
      password: tabuyos

spring:
  quartz:
    job-store-type: jdbc
