server:
  port: 8080

dubbo:
  protocol:
    name: dubbo
    port: -1
  application:
    name: nacos-dubbo
  registry:
    #    使用 nacos 作为注册中心
    address: nacos://127.0.0.1:8848
#    使用 zookeeper 作为注册中心
#    address: zookeeper://localhost:2181
#    自定义命名空间方式
#    第一种
#    address: nacos://localhost:8848?namespace=xxx-xxx-xxx
#    第二种
#    parameters:
#      namespace: xxx-xxx-xxx
demo:
  service:
    name: demoService
    version: 1.0.0
