server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/tabuyos?useUnicode=true&characterEncoding=utf8
    username: tabuyos
    password: tabuyos
